# .github/workflows/daily_scrape.yml

name: Daily PlayStation Price Check

on:
  schedule:
    - cron: '0 5 * * *' # Her gün sabah 05:00 UTC'de çalışır
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape_and_report:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository'deki kodları ve mevcut veritabanını indir
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. Python ortamını kur
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Gerekli kütüphaneleri yükle
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Kazıma betiğini çalıştırarak yeni tabloyu ekle
      - name: Run Scraper to get latest prices
        run: python scripts/scrape_and_update_db.py

      # 5. İndirim raporunu oluştur
      - name: Generate discount report
        run: python scripts/generate_discount_report.py

      # 6. Değişen dosyaları (veritabanı ve rapor) commit'le
      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add playstation_games.db DISCOUNTS.md
          # Commit mesajındaki tarihi İstanbul saatine göre ayarla
          COMMIT_MESSAGE="Update: Daily prices and report for $(TZ='Europe/Istanbul' date +'%d-%m-%Y %H:%M')"
          git commit -m "$COMMIT_MESSAGE"
          git push
