# .github/workflows/daily_scrape.yml

name: Daily PlayStation Price Check

on:
  schedule:
    - cron: '0 5 * * *' 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape_and_report:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraper to get latest prices
        env: # <-- BU BLOK ÇOK ÖNEMLİ
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python scripts/scrape_and_update_db.py

      - name: Generate discount report
        env: # <-- BU BLOK ÇOK ÖNEMLİ
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python scripts/generate_discount_report.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@github.com'
          git add playstation_games.db DISCOUNTS.md
          # Değişiklik varsa commit at
          git diff --staged --quiet || git commit -m "Update: Daily prices and discount report for $(date -u +'%d-%m-%Y')"
          git push
