# .github/workflows/daily_scrape.yml

name: Daily PlayStation Price Check

on:
  schedule:
    - cron: '0 5 * * *' # Her gün sabah 05:00 UTC'de çalışır
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape_and_report:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraper to get latest prices
        run: python scripts/scrape_and_update_db.py

      - name: Generate discount report
        run: python scripts/generate_discount_report.py

      # --- YENİ HATA AYIKLAMA ADIMLARI ---
      - name: 'DEBUG: Show file changes'
        run: |
          echo "--- Checking for changes with 'git status' ---"
          git status

      - name: 'DEBUG: Display report content'
        run: |
          echo "--- Content of DISCOUNTS.md ---"
          cat DISCOUNTS.md || echo "DISCOUNTS.md not found or is empty."
          echo "-------------------------------"

      # -------------------------------------

      - name: Check for file changes
        id: check_changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected in the repository."
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected. Proceeding with notification and commit."
          fi

      - name: Read discount report file
        id: read_report
        if: steps.check_changes.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          REPORT_CONTENT=$(cat DISCOUNTS.md | head -c 4000)
          echo "report_content<<EOF" >> $GITHUB_OUTPUT
          echo "$REPORT_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Send Telegram Notification
        # Sadece değişiklik varsa veya manuel çalıştırıldıysa bildirim gönder
        if: steps.check_changes.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: ${{ steps.read_report.outputs.report_content }}
          format: markdown

      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add playstation_games.db DISCOUNTS.md
          git commit -m "Update: Daily prices and discount report for $(date -u +'%d-%m-%Y')"
          git push
